spring.profiles.active=@spring.profiles.active@

spring.config.import=${HOME}/conf/ipgeolocation/database-reader-config.yaml

logging.level.io.ipgeolocation.databaseReader=INFO

application.country.EUCountryCodeISO2List=DE,HR,IT,FR,PL,ES,SE,RO,BG,GR,NL,HU,CZ,AT,IE,DK,BE,PT,FI,SI,CY,MT,LT,SK,LV,EE,LU
cloud.asn.download.url=https://cloud-asns.ipgeolocation.io/ip-security-api/v3/download-cloud-asn/k87o8qw5gbhnm96bo7jrofcsgh4rusemq63zs